import { useEffect, useState } from 'react';
import type { ReadingToken } from '@/domain/schema';
import { loadWordStudy, wordStudyForToken, type WordStudyData, type WordStudyEntry } from '@/io/wordstudy';

/**
 * "Word study" section of the detail panel: gloss distribution (Berean
 * Interlinear `@gloss`, generated by `scripts/generate/wordstudy.ts`) plus
 * Strong's-dictionary derivation. Renders under the immediate-detail rows
 * (DetailPanel.tsx) — this section alone is async/lazy; everything above it
 * is unchanged and synchronous.
 *
 * Hebrew has no data this PR (documented limitation, ADR-0002) — it always
 * shows the truthful "not available yet" state rather than attempting a
 * fetch that could never succeed.
 */

type WordStudyState =
  | { kind: 'hebrew' }
  | { kind: 'loading' }
  | { kind: 'error' }
  | { kind: 'missing' }
  | { kind: 'ready'; entry: WordStudyEntry; meta: WordStudyData['meta'] };

/** Bars shown before folding the rest into "Other (n)". */
const TOP_GLOSSES = 8;

export function WordStudySection({
  token,
  openStrongs,
}: {
  token: Pick<ReadingToken, 'language' | 'strong' | 'lemma'>;
  openStrongs: (query: string) => void;
}) {
  const [state, setState] = useState<WordStudyState>(
    token.language !== 'grc' ? { kind: 'hebrew' } : { kind: 'loading' },
  );

  useEffect(() => {
    if (token.language !== 'grc') {
      setState({ kind: 'hebrew' });
      return;
    }
    setState({ kind: 'loading' });
    let cancelled = false;
    loadWordStudy()
      .then((data) => {
        if (cancelled) return;
        if (!data) {
          setState({ kind: 'error' });
          return;
        }
        const entry = wordStudyForToken(data, token);
        setState(entry ? { kind: 'ready', entry, meta: data.meta } : { kind: 'missing' });
      })
      .catch(() => {
        if (!cancelled) setState({ kind: 'error' });
      });
    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps -- token identity captured via its fields
  }, [token.language, token.strong, token.lemma]);

  return (
    <section className="word-study" aria-label="Word study">
      <h3 className="word-study-heading">Word study</h3>
      {state.kind === 'hebrew' || state.kind === 'missing' ? (
        <p className="notice ws-notice">Word-study data isn’t available for this word yet.</p>
      ) : state.kind === 'loading' ? (
        <p className="notice ws-notice">Loading word study…</p>
      ) : state.kind === 'error' ? (
        <p className="notice ws-notice error">
          Word-study data couldn’t be loaded (offline, or not downloaded yet).
        </p>
      ) : (
        <WordStudyReady entry={state.entry} openStrongs={openStrongs} />
      )}
    </section>
  );
}

function WordStudyReady({
  entry,
  openStrongs,
}: {
  entry: WordStudyEntry;
  openStrongs: (query: string) => void;
}) {
  const glossed = entry.g.reduce((sum, [, n]) => sum + n, 0);
  const top = entry.g.slice(0, TOP_GLOSSES);
  const rest = entry.g.slice(TOP_GLOSSES);
  const otherCount = rest.reduce((sum, [, n]) => sum + n, 0);
  const scale = Math.max(top[0]?.[1] ?? 0, otherCount, 1);
  const pct = (n: number) => (glossed > 0 ? (n / glossed) * 100 : 0);

  return (
    <>
      <p className="ws-total">
        <strong>{entry.t.toLocaleString()}×</strong> in the Greek NT
      </p>

      {entry.r === 'derived' && entry.d && entry.d.length > 0 && (
        <div className="row ws-derivation">
          <dt>Derived from</dt>
          <dd>
            {entry.d.map((num, i) => (
              <span key={num}>
                {i > 0 && ', '}
                <button type="button" className="link" onClick={() => openStrongs(`G${num}`)}>
                  G{num}
                </button>
              </span>
            ))}
            {entry.dt && <span className="ws-dt"> — {entry.dt}</span>}
          </dd>
        </div>
      )}
      {entry.r === 'root' && (
        <div className="row ws-derivation">
          <dt>Root</dt>
          <dd>{entry.dt ?? 'A primary word — not derived from another Greek root.'}</dd>
        </div>
      )}

      {entry.g.length > 0 ? (
        <>
          <h4 className="ws-subheading">Gloss distribution</h4>
          <ul className="ws-bars">
            {top.map(([gloss, n]) => (
              <li key={gloss} className="ws-bar-row">
                <span className="ws-bar-label">{gloss}</span>
                <span className="ws-bar-track">
                  <span className="ws-bar-fill" style={{ width: `${(n / scale) * 100}%` }} />
                </span>
                <span className="ws-bar-count">
                  {n} <span className="ws-bar-pct">({pct(n).toFixed(0)}%)</span>
                </span>
              </li>
            ))}
            {rest.length > 0 && (
              <li className="ws-bar-row ws-bar-other">
                <span className="ws-bar-label">Other ({rest.length})</span>
                <span className="ws-bar-track">
                  <span className="ws-bar-fill" style={{ width: `${(otherCount / scale) * 100}%` }} />
                </span>
                <span className="ws-bar-count">
                  {otherCount} <span className="ws-bar-pct">({pct(otherCount).toFixed(0)}%)</span>
                </span>
              </li>
            )}
          </ul>
          <p className="ws-note">
            {glossed.toLocaleString()} glossed occurrence{glossed === 1 ? '' : 's'}
            {glossed !== entry.t ? ` of ${entry.t.toLocaleString()} total` : ''}.
          </p>

          <details className="ws-details">
            <summary>All {entry.g.length} gloss{entry.g.length === 1 ? '' : 'es'}</summary>
            <div className="ws-table-scroll">
              <table className="ws-table">
                <caption className="sr-only">
                  Gloss distribution: gloss, occurrence count, percent of glossed occurrences
                </caption>
                <thead>
                  <tr>
                    <th scope="col">Gloss</th>
                    <th scope="col">Count</th>
                    <th scope="col">% of glossed</th>
                  </tr>
                </thead>
                <tbody>
                  {entry.g.map(([gloss, n]) => (
                    <tr key={gloss}>
                      <td>{gloss}</td>
                      <td>{n}</td>
                      <td>{pct(n).toFixed(1)}%</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </details>
        </>
      ) : (
        <p className="notice ws-notice">No glossed occurrences for this word.</p>
      )}
    </>
  );
}
